/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NetworkIdentifier from './NetworkIdentifier';
import Operation from './Operation';

/**
 * The ConstructionPreprocessRequest model module.
 * @module model/ConstructionPreprocessRequest
 * @version 1.4.1
 */
class ConstructionPreprocessRequest {
    /**
     * Constructs a new <code>ConstructionPreprocessRequest</code>.
     * ConstructionPreprocessRequest is passed to the &#x60;/construction/preprocess&#x60; endpoint so that a Rosetta implementation can determine which metadata it needs to request for construction.
     * @alias module:model/ConstructionPreprocessRequest
     * @param networkIdentifier {module:model/NetworkIdentifier} 
     * @param operations {Array.<module:model/Operation>} 
     */
    constructor(networkIdentifier, operations) { 
        
        ConstructionPreprocessRequest.initialize(this, networkIdentifier, operations);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, networkIdentifier, operations) { 
        obj['network_identifier'] = networkIdentifier;
        obj['operations'] = operations;
    }

    /**
     * Constructs a <code>ConstructionPreprocessRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConstructionPreprocessRequest} obj Optional instance to populate.
     * @return {module:model/ConstructionPreprocessRequest} The populated <code>ConstructionPreprocessRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConstructionPreprocessRequest();

            if (data.hasOwnProperty('network_identifier')) {
                obj['network_identifier'] = NetworkIdentifier.constructFromObject(data['network_identifier']);
            }
            if (data.hasOwnProperty('operations')) {
                obj['operations'] = ApiClient.convertToType(data['operations'], [Operation]);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/NetworkIdentifier} network_identifier
 */
ConstructionPreprocessRequest.prototype['network_identifier'] = undefined;

/**
 * @member {Array.<module:model/Operation>} operations
 */
ConstructionPreprocessRequest.prototype['operations'] = undefined;

/**
 * @member {Object} metadata
 */
ConstructionPreprocessRequest.prototype['metadata'] = undefined;






export default ConstructionPreprocessRequest;

