/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Operation from './Operation';

/**
 * The ConstructionParseResponse model module.
 * @module model/ConstructionParseResponse
 * @version 1.4.1
 */
class ConstructionParseResponse {
    /**
     * Constructs a new <code>ConstructionParseResponse</code>.
     * ConstructionParseResponse contains an array of operations that occur in a transaction blob. This should match the array of operations provided to &#x60;/construction/preprocess&#x60; and &#x60;/construction/payloads&#x60;.
     * @alias module:model/ConstructionParseResponse
     * @param operations {Array.<module:model/Operation>} 
     * @param signers {Array.<String>} All signers of a particular transaction. If the transaction is unsigned, it should be empty.
     */
    constructor(operations, signers) { 
        
        ConstructionParseResponse.initialize(this, operations, signers);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, operations, signers) { 
        obj['operations'] = operations;
        obj['signers'] = signers;
    }

    /**
     * Constructs a <code>ConstructionParseResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConstructionParseResponse} obj Optional instance to populate.
     * @return {module:model/ConstructionParseResponse} The populated <code>ConstructionParseResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConstructionParseResponse();

            if (data.hasOwnProperty('operations')) {
                obj['operations'] = ApiClient.convertToType(data['operations'], [Operation]);
            }
            if (data.hasOwnProperty('signers')) {
                obj['signers'] = ApiClient.convertToType(data['signers'], ['String']);
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Operation>} operations
 */
ConstructionParseResponse.prototype['operations'] = undefined;

/**
 * All signers of a particular transaction. If the transaction is unsigned, it should be empty.
 * @member {Array.<String>} signers
 */
ConstructionParseResponse.prototype['signers'] = undefined;

/**
 * @member {Object} metadata
 */
ConstructionParseResponse.prototype['metadata'] = undefined;






export default ConstructionParseResponse;

